# Generated by Django 5.1.3 on 2024-11-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_expertteam_siteedit_facebooklink_siteedit_instergram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('idx', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='projext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('idx', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='expertteam',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
